// Generated by CoffeeScript 1.3.3
(function() {
  var async, configureExpress, configureLogging, configureRestless, createExpress, express, namespace, startExpress, winston;

  namespace = require('require-namespace');

  express = require('express');

  async = require('async');

  winston = require('winston');

  createExpress = function(done) {
    winston.info("Creating express.");
    global.app = express(express.cookieParser(), express.bodyParser(), express.session({
      secret: 'A secretie valUe'
    }));
    return done();
  };

  configureExpress = function(done) {
    winston.info("Configuring express.");
    app.configure('development', function() {
      app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
      return app.use(express["static"](__dirname + '/public'));
    });
    return done();
  };

  startExpress = function(done) {
    var port;
    winston.info("Starting express.");
    port = process.env.PORT || 3050;
    return app.listen(port, function() {
      winston.info("Express server listening on port " + port + " in " + app.settings.env + " mode.");
      return done();
    });
  };

  configureLogging = function(done) {
    winston.handleExceptions();
    return done(null, null);
  };

  configureRestless = function(done) {
    winston.info("Configuring restless");
    return done();
  };

  async.series([configureLogging, createExpress, configureExpress, configureRestless, startExpress]);

}).call(this);
