// Generated by CoffeeScript 1.3.3
(function() {
  var async, configureLogging, configureRestless, createExpress, express, inspect, namespace, processSeriesResult, restless, startExpress, winston;

  namespace = require('require-namespace');

  express = require('express');

  async = require('async');

  winston = require('winston');

  restless = require('../index');

  inspect = require('util').inspect;

  require('longjohn');

  createExpress = function(done) {
    winston.info("Creating express.");
    global.app = express();
    app.use(express.logger());
    app.configure('development', function() {
      return app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
    });
    app.use(express.bodyParser());
    return done();
  };

  configureRestless = function(done) {
    return restless.configureResourcesInDirectory(__dirname + '/resources', done);
  };

  startExpress = function(done) {
    var port;
    winston.info("Express is now starting.");
    port = process.env.PORT || 3050;
    winston.info("Routes: " + inspect(app.routes));
    return app.listen(port, function() {
      winston.info("Express server listening on port " + port + " in " + app.settings.env + " mode.");
      winston.info('Please go to "http://localhost:3050/people/0" to start your exciting journey.');
      return done();
    });
  };

  configureLogging = function(done) {
    winston.handleExceptions();
    return done();
  };

  processSeriesResult = function(err) {
    if (err) {
      return winston.error(err.toString());
    }
  };

  async.series([configureLogging, createExpress, configureRestless, startExpress], processSeriesResult);

}).call(this);
