// Generated by CoffeeScript 1.3.3
(function() {
  var Resource, cache;

  Resource = require('../../lib/resource/Resource');

  cache = require('../../lib/caching/cache');

  module.exports = new Resource({
    url: "/address/:id",
    cache: cache.forever().publically(),
    respondsTo: [
      {
        get: function(id) {
          var address;
          return address = {
            "House Name/Number": 72,
            "Stree Name": "Fox Lane",
            "Town": "Edinburgh",
            "PostCode": "EH99 7JJ"
          };
        }
      }
    ]
  });

}).call(this);
