// Generated by CoffeeScript 1.3.3
(function() {
  var Resource, caching, http, people;

  Resource = require('../../lib/resource/Resource');

  http = require('../../lib/resource/http');

  caching = require('../../lib/caching/cache');

  people = [
    {
      firstName: "bob",
      lastName: "smith"
    }, {
      firstName: "francis",
      lastName: "smith"
    }, {
      firstName: "bill",
      lastName: "bridge"
    }, {
      firstName: "edgar",
      lastName: "jones"
    }, {
      firstName: "lily",
      lastName: "wright"
    }, {
      firstName: "mike",
      lastName: "terry"
    }, {
      firstName: "sarah",
      lastName: "connors"
    }, {
      firstName: "dorothy",
      lastName: "fibbers"
    }
  ];

  module.exports = new Resource({
    url: "/people",
    cache: caching.minutes(5).publically(),
    respondsTo: [
      http.get(function(from, to) {
        require('util').log("From: " + from);
        return " ************** OK *************** ";
      })
    ]
  });

}).call(this);
