// Generated by CoffeeScript 1.3.3
(function() {
  var Resource, caching, ensureNumericId, http, puppyChangeProcessor, puppySchema;

  Resource = require('../../../lib/resource/Resource');

  http = require('../../../lib/resource/http');

  caching = require('../../../lib/caching/cache');

  ensureNumericId = require('./ensureNumericId');

  puppySchema = require('./puppySchema');

  puppyChangeProcessor = require('./puppyChangeProcessor');

  module.exports = new Resource({
    url: "/puppies/:id",
    cache: caching.minutes(5).publically(),
    respondsTo: [
      {
        get: function(id) {
          return {
            name: "spot"
          };
        },
        "arguments": ensureNumericId
      }, {
        put: function(id, body) {
          return puppyChangeProcessor(original, body, this.populateResponse);
        },
        "arguments": ensureNumericId,
        body: puppySchema
      }
    ]
  });

}).call(this);
