// Generated by CoffeeScript 1.3.3
(function() {
  var mustBe, now;

  mustBe = require('rules').mustBe;

  now = require('rules').now;

  module.exports = {
    name: mustBe().populated().string({
      maxLength: 50
    }),
    dateOfBirth: mustBe().date({
      before: now()
    }),
    neutered: mustBe().boolean(),
    cell: mustBe().string()
  };

}).call(this);
